static Glib::ustring ui_builder =
"<?xml version='1.0' encoding='UTF-8'?>"
"<interface>"
"  <!-- interface-requires gtk+ 3.0 -->"
"  <object class='GtkAdjustment' id='adjustment1'>"
"    <property name='lower'>5</property>"
"    <property name='upper'>600</property>"
"    <property name='value'>60</property>"
"    <property name='step_increment'>1</property>"
"    <property name='page_increment'>10</property>"
"  </object>"
"  <object class='GtkDialog' id='preferences'>"
"    <property name='can_focus'>False</property>"
"    <property name='border_width'>5</property>"
"    <property name='title' translatable='yes'>pdfMelange-preferences</property>"
"    <property name='type_hint'>dialog</property>"
"    <child internal-child='vbox'>"
"      <object class='GtkBox' id='dialog-vbox1'>"
"        <property name='can_focus'>False</property>"
"        <property name='orientation'>vertical</property>"
"        <property name='spacing'>2</property>"
"        <child>"
"          <object class='GtkGrid' id='grid1'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='row_spacing'>2</property>"
"            <property name='column_spacing'>2</property>"
"            <child>"
"              <object class='GtkLabel' id='labelIconSize'>"
"                <property name='width_request'>54</property>"
"                <property name='height_request'>20</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='xalign'>0</property>"
"                <property name='label' translatable='yes'>Iconsize</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>1</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkSpinButton' id='spinButtonIconSize'>"
"                <property name='width_request'>100</property>"
"                <property name='height_request'>25</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='max_length'>3</property>"
"                <property name='invisible_char'>•</property>"
"                <property name='invisible_char_set'>True</property>"
"                <property name='progress_fraction'>0.0099999997764825821</property>"
"                <property name='progress_pulse_step'>0.10000000149011612</property>"
"                <property name='adjustment'>adjustment1</property>"
"                <property name='climb_rate'>0.10000000000000001</property>"
"                <property name='numeric'>True</property>"
"                <property name='wrap'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>1</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='labelPageMode'>"
"                <property name='width_request'>175</property>"
"                <property name='height_request'>20</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='xalign'>0</property>"
"                <property name='label' translatable='yes'>Viewer startup pagemode</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>2</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkComboBoxText' id='comboBoxTextPageMode'>"
"                <property name='width_request'>150</property>"
"                <property name='height_request'>27</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='entry_text_column'>0</property>"
"                <property name='id_column'>1</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>2</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='labelPageLayout'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='xalign'>0</property>"
"                <property name='label' translatable='yes'>Viewer startup pagelayout</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>3</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkComboBoxText' id='comboBoxTextPageLayout'>"
"                <property name='width_request'>150</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='entry_text_column'>0</property>"
"                <property name='id_column'>1</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>3</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkCheckButton' id='checkLogging'>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>False</property>"
"                <property name='halign'>start</property>"
"                <property name='valign'>center</property>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='xalign'>0</property>"
"                <property name='draw_indicator'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>0</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='label1'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='halign'>start</property>"
"                <property name='label' translatable='yes'>Activate message logging to a file</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>0</property>"
"                <property name='width'>1</property>"
"                <property name='height'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>True</property>"
"            <property name='position'>0</property>"
"          </packing>"
"        </child>"
"        <child internal-child='action_area'>"
"          <object class='GtkButtonBox' id='dialog-action_area1'>"
"            <property name='can_focus'>False</property>"
"            <property name='layout_style'>end</property>"
"            <child>"
"              <object class='GtkButton' id='cancel'>"
"                <property name='label' translatable='yes'>Cancel</property>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='yalign'>0.52999997138977051</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='save'>"
"                <property name='label' translatable='yes'>Save</property>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_action_appearance'>False</property>"
"                <property name='xalign'>0.51999998092651367</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>True</property>"
"            <property name='pack_type'>end</property>"
"            <property name='position'>0</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"    <action-widgets>"
"      <action-widget response='0'>cancel</action-widget>"
"      <action-widget response='0'>save</action-widget>"
"    </action-widgets>"
"  </object>"
"</interface>";
